### ISSUE TITLE
tumbler.com/archive ??

### ISSUE THREAD

**Issue by EC-O-DE** [jtank4/Better-Tumblr-Video#1]
Archive pages is it possible to show Plyr? And/or HTML5 default but with volume slider?

**Comment by jtank4** [comment]
Hello EC-O-DE, thanks for your suggestion.
Unfortunately, while it might be possible, but it would be at least a little gross and imprecise. Those "videos" on the archive page are actually just links, so an HTTP request would have to be made to look at the page it links to, and then again in that page to look at the iframe to get the source. But between those steps, you have to know exactly what video to look for, and the link does not necessarily have that information. So, sorry, but I'm not going to add that functionality. Also, I apologize it took me so long to respond.
